# builds image for the agents backend
FROM python:3.10

WORKDIR backend

# need cmake for scikit
RUN apt-get update && apt-get install -y python3-pip cmake netcat-openbsd

COPY ./backend/requirements.txt ./requirements.txt

RUN pip install -r ./requirements.txt

# expose python server port
EXPOSE 1235

# start startup script
CMD sh ./startup.sh